#-------------------------------
# General Site Settings

title: Marcus Bale
logo: 
author: Marcus Bale
description: this is meta description
email: marcusbale.inlondon@gmail.com
# phone: +880 2544 658 256
# address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
# - {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: marcusb # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Marcus <br> and I love product

social:

- {icon: "ti-linkedin", link: "https://uk.linkedin.com/in/marcus-bale"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Welcome to my blog space! I'm a tech and gaming obsessed Product Director with over 7 years of experience managing and delivering products across startups and enterprises.
  <br>
  Over that period I've learnt a lot about product strategy, user research and data analysis, and I plan to share some my of thoughts and experiences here.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
# team:
#   - title : "Jack Schenziwe"
#     image : "assets/images/team/member-1.png"
#     designation : "Project Manager"
    
#   - title : "Julias Carlie"
#     image : "assets/images/team/member-2.png"
#     designation : "Web Developer"
    
#   - title : "John Doe"
#     image : "assets/images/team/member-3.png"
#     designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Analysis, color: '#B8336A', value: '95%'}
- {name: Communication, color: '#FFB2E6', value: '85%'}
- {name: Creativity, color: '#1C7293', value: '80%'}
- {name: Agile Delivery, color: '#F7996E', value: '95%'}
- {name: User Empathy, color: '#F7996E', value: '90%'}
- {name: Leadership, color: '#1C7293', value: '75%'}
- {name: Product Strategy, color: '#FFB2E6', value: '70%'}
- {name: Problem Solving, color: '#B8336A', value: '85%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Product Director, icon: 'bigsofa_icon.png', date: 'Jul 2020 - Present', organization: 'BIG SOFA TECHNOLOGIES'}
- {name: Senior Product Manager, icon: 'bigsofa_icon.png', date: 'Jul 2019 - Jun 2020', organization: 'BIG SOFA TECHNOLOGIES'}
- {name: Product Manager, icon: 'bigsofa_icon.png', date: 'Jun 2018 - Jun 2019', organization: 'BIG SOFA TECHNOLOGIES'}
- {name: Product Owner, icon: 'macmillan_icon.png', date: 'Jun 2017 - Jun 2018', organization: 'MACMILLAN EDUCATION'}
- {name: Agile Business Analyst, icon: 'sky_icon.png', date: 'Jan 2016 - Jun 2017', organization: 'SKY'}
- {name: Technical Analyst, icon: 'sky_icon.png', date: 'Jun 2015 - Jan 2016', organization: 'SKY'}
- {name: Associate Software Engineer, icon: 'sky_icon.png', date: 'Jul 2014 - Jun 2015', organization: 'SKY'}
- {name: Business Analyst (Internship), icon: 'ge_icon.png', date: 'Jul 2012 - Jul 2013', organization: 'GE Capital'}



#-------------------------------
# Education Section

education-title: Education
education:
- {name: BSc Computing and Mathematics (First Class), date: '2014', organization: 'University of the West of England'}
- {name: A-Levels, date: '2010', organization: 'Holyrood Academy'}



#-------------------------------
# Services Section

services-title: Competencies 
services:
- {
    name: Product Strategy,
    icon: ti-palette,
    description: 'Skilled at analysing and balancing competing needs, articulating a product vision and prioritising features into an achieve-able roadmap.',
    active: true # Add true to select section
  }
- {
    name: User Research & UX Design,
    icon: ti-vector,
    description: 'Experience conducting user research interviews, usability tests and designing wireframes using Sketch and other inVision.',
    active:  # Add true to select section
  }
- {
    name: AI & Machine Learning,
    icon: ti-panel,
    description: 'Understanding of the process of developing AI and ML algorithms. Experience researching, analysing and integrating AI engines including text analytics, NLP, image recognition and audio analysis to facial coding and emotion detection.',
    active: true # Add true to select section
  }
- {
    name: Data Analysis,
    icon: ti-panel,
    description: 'Comfortable extracting, analysing and visualising large datasets using a variety of tools and using this to inform product decisions.',
    active: # Add true to select section
  }
- {
    name: Networking & Communication,
    icon: ti-panel,
    description: 'E!ective at building relationships with clients, users, stakeholders, suppliers and team members. Able to tailor communications to convey information at an appropriate level for the target audience.',
    active: # Add true to select section
  }
- {
    name: Agile Practices,
    icon: ti-panel,
    description: 'Keen interest in Agile methodology with experience working within Scrum and Kanban development teams.',
    active: # Add true to select section
  }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
# portfolio-home-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-4.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"


# Portfolio Page
# portfolio-label:
# - {
#     title : "UI/UX Design",
#     type : "design"
#   }
# - {
#     title : "BRANDING",
#     type : "branding"
#   }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }

# portfolio-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#      - type: "design"
#      - type: "illustration"
      
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
      
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section


contact-title: Contact Info
contact-email: marcusbale.inlondon@gmail.com
